import * as items from "./constants.js";
import { ConstantSet } from "./utils/setUtils.js";

globalThis.d0701 = new ConstantSet([
  items.spinach,
  items.peas,
  items.redPeppers,
  items.carrots,
  items.garlic,
  items.lemon,
  items.mungBeans,
  items.coriander,
  items.blackPeppercorns,
  items.avocado,
  items.kiwi,
  items.cucumbers,
  items.apple,
  items.coffee,
  items.pistachios,
  items.cumin,
]);

globalThis.d0702 = new ConstantSet([
  items.avocado,
  items.kiwi,
  items.chocolate,
  items.coffee,
  items.greenTea,
  items.cardamom,
  items.coriander,
  items.apple,
  items.carrots,
  items.spinach,
  items.peas,
  items.redPeppers,
  items.sesame,
]);

globalThis.d0703 = new ConstantSet([
  items.asian_huangqi,
  items.gojiBerries,
  items.asian_daylily,
  items.asian_solomonsSeal,
  items.kale,
  items.haricotsVerts,
  items.tomatoes,
  items.oatmeal,
  items.apple,
  items.soybeans,
  items.broccoli,
  items.sesame,
  items.blackbeans,
  items.blueberries,
  items.coffee,
]);

globalThis.d0704 = new ConstantSet([
  items.potatoes,
  items.purplepotatoes,
  items.kiwi,
  items.apple,
  items.coffee,
  items.asian_huangqi,
  items.gojiBerries,
  items.asian_daylily,
  items.asian_solomonsSeal,
  items.kale,
  items.haricotsVerts,
  items.tomatoes,
  items.greenTea,
  items.assamTea,
  items.lemon,
  items.blueberries,
  items.cranberries,
  items.pistachios,
  items.broccoli,
  items.spinach,
  items.carrots,
  items.celery,
  items.yellowPeppers,
  items.greenPeppers,
  items.turmeric,
  items.redPeppers,
  items.cumin,
  items.mushrooms,
  items.gobou,
  items.chrysanthemumTea,
  items.fermentedGarlic,
]);

globalThis.d0705 = new ConstantSet([
  items.broccoli,
  items.spinach,
  items.carrots,
  items.celery,
  items.yellowPeppers,
  items.greenPeppers,
  items.turmeric,
  items.redPeppers,
  items.cumin,
  items.mushrooms,
  items.gobou,
  items.chrysanthemumTea,
  items.mango,
]);

globalThis.d0705 = new ConstantSet([
  items.broccoli,
  items.spinach,
  items.carrots,
  items.celery,
  items.yellowPeppers,
  items.greenPeppers,
  items.turmeric,
  items.redPeppers,
  items.cumin,
  items.mushrooms,
  items.gobou,
  items.mango,
  items.hazelnuts,
  items.cashews,
  items.almonds,
  items.walnuts,
  items.raisins,
  items.greenTea,
]);

globalThis.d0707 = new ConstantSet([
  items.damianaTea,
  items.greenTea,
  items.mango,
  items.hazelnuts,
  items.cashews,
  items.almonds,
  items.walnuts,
  items.raisins,
  items.redOnion,
  items.potatoes,
]);

globalThis.d0708 = new ConstantSet([
  items.greenTea,
  items.mango,
  items.hazelnuts,
  items.cashews,
  items.almonds,
  items.walnuts,
  items.raisins,
  items.cabbage,
  items.seaweed,
  items.coffee,
  items.edamame,
]);

globalThis.d0709 = new ConstantSet([
  items.greenTea,
  items.hazelnuts,
  items.cashews,
  items.almonds,
  items.walnuts,
  items.tomatoes,
  items.springOnion,
  items.eggPlants,
  items.spinach,
  items.blackPeppercorns,
  items.yellowPeppers,
  items.celery,
  items.lotusRoots,
]);

globalThis.d0710 = new ConstantSet([
  items.apple,
  items.cucumbers,
  items.pistachios,
  items.blackCarrotJuice,
  items.greenTea,
  items.coffee,
  items.cinnamon,
  items.nutmeg,
  items.cloves,
  items.tomatoes,
  items.springOnion,
  items.eggPlants,
  items.spinach,
  items.blackPeppercorns,
  items.yellowPeppers,
  items.celery,
  items.lotusRoots,
]);

globalThis.d0710 = new ConstantSet([
  items.mandarin,
  items.greenTea,
  items.mango,
  items.pistachios,
  items.blackCarrotJuice,
  items.mungBeans,
  items.redOnion,
  items.celery,
  items.tomatoes,
  items.yellowPeppers,
  items.greenPeppers,
  items.redPeppers,
  items.olives,
  items.potatoes,
  items.purplepotatoes,
  items.fermentedGarlic,
  items.garlic,
]);

globalThis.d0712 = new ConstantSet([
  items.apple,
  items.zucchini,
  items.mango,
  items.eggPlants,
  items.tomatoes,
  items.redPeppers,
  items.beets,
  items.yellowPeppers,
  items.chickpeas,
  items.blackbeans,
  items.spinach,
  items.purpleRice,
  items.redOnion,
  items.heartOfPalm,
  items.cucumbers,
  items.capers,
  items.edamame,
  items.mushrooms,
  items.mint,
  items.greenApples,
  items.papayas,
  items.watermelon,
  items.basil,
  items.romainLettuce,
  items.olives,
  items.pistachios,
  items.corn,
  items.califlower,
  items.artichokes,
  items.quinoa,
  items.celery,
  items.jalapeño,
  items.papayas,
  items.pickledPepino,
  items.favaBeans,
]); // fogo de chao

globalThis.d0713 = new ConstantSet([
  items.haricotsVerts,
  items.broccoli,
  items.carrots,
  items.redOnion,
  items.blackCarrotJuice,
  items.fermentedGarlic,
  items.kale,
  items.pistachios,
  items.ginger,
  items.asian_huangqi,
  items.asian_solomonsSeal,
  items.gojiBerries,
  items.chrysanthemumTea,
  items.greenTea,
  items.mandarin,
  items.avocado,
]);

globalThis.d0714 = new ConstantSet([
  items.haricotsVerts,
  items.broccoli,
  items.carrots,
  items.redOnion,
  items.blackCarrotJuice,
  items.fermentedGarlic,
  items.kale,
  items.pistachios,
  items.ginger,
  items.asian_huangqi,
  items.asian_solomonsSeal,
  items.gojiBerries,
  items.chrysanthemumTea,
  items.greenTea,
  items.mandarin,
  items.avocado,
  items.tomatoes,
  items.apple,
  items.mandarin,
]);

globalThis.d0715 = new ConstantSet([
  items.lime,
  items.mandarin,
  items.asian_huangqi,
  items.asian_solomonsSeal,
  items.olives,
  items.gojiBerries,
  items.blackbeans,
  items.chrysanthemumTea,
  items.sesame,
  items.soybeans,
]);

globalThis.d0716 = new ConstantSet([
  items.asian_solomonsSeal,
  items.blackbeans,
  items.chrysanthemumTea,
  items.sesame,
  items.soybeans,
  items.broccoli,
  items.tomatoes,
  items.celery,
  items.greenOnion,
  items.chiaSeeds,
  items.chickpeas,
  items.garlic,
  items.ginger,
  items.blackPeppercorns,
  items.SichuanPeppers,
  items.pistachios,
  items.coffee,
  items.cinnamon,
  items.nutmeg,
]);

globalThis.d0722 = new ConstantSet([
  items.mint,
  items.ginger,
  items.assamTea,
  items.turmeric,
  items.blackPeppercorns,
  items.chickpeas,
  items.farro,
  items.kale,
  items.celery,
  items.tomatoes,
  items.garlic,
  items.haricotsVerts,
  items.cumin,
]);

globalThis.d0723 = new ConstantSet([
  items.tomatoes,
  items.celery,
  items.redPeppers,
  items.kale,
  items.spinach,
  items.corn,
  items.apple,
  items.nettleLeaves,
  items.SichuanPeppers,
  items.chocolate,
  items.coffee,
  items.garlic,
]);

globalThis.d0727 = new ConstantSet([
  items.thymeTea,
  items.greenTea,
  items.apple,
  items.celery,
  items.carrots,
  items.cabbage,
  items.sweetPotaotes,
  items.radish,
  items.ginger,
  items.garlic,
  items.spinach,
  items.chocolate,
  items.cinnamon,
  items.cloves,
  items.SichuanPeppers,
  items.fennelSeeds,
  items.coriander,
  items.anise,
]);

globalThis.d0728 = new ConstantSet([
  items.almonds,
  items.walnuts,
  items.oatmeal,
  items.farro,
  items.kimchi,
  items.redOnion,
  items.tomatoes,
  items.whitePeppers,
  items.cinnamon,
  items.cloves,
  items.greenTea,
  items.coffee,
  items.nettleLeaves,
  items.garlic,
  items.nutmeg,
  items.quinoa,
  items.greenPeppers,
  items.yellowPeppers,
  items.seaweed,
  items.edamame,
  items.plum,
  items.blackbeans,
  items.sesame,
  items.chiaSeeds,
  items.asian_chinese_pearl_barley,
  items.asian_chinese_yam,
  items.asian_lotus_seeds,
  items.asian_qian_shi,
  items.gojiBerries,
  items.asian_dong_quai,
]);

globalThis.d0729 = new ConstantSet([
  items.chiaSeeds,
  items.asian_chinese_pearl_barley,
  items.asian_chinese_yam,
  items.asian_lotus_seeds,
  items.asian_qian_shi,
  items.gojiBerries,
  items.asian_dong_quai,
  items.assamTea,
  items.mint,
  items.thymeTea,
  items.redOnion,
  items.garlic,
  items.ginger,
  items.spinach,
  items.lime,
  items.peanuts,
  items.oatmeal,
  items.cabbage,
  items.nutmeg,
  items.coffee,
  items.carrots,
  items.whitePeppers,
]);

globalThis.d0730 = new ConstantSet([
  items.oatmeal,
  items.mint,
  items.assamTea,
  items.honey,
  items.cloves,
  items.nutmeg,
  items.chiaSeeds,
  items.peanuts,
  items.blueberries,
  items.cranberries,
  items.turmeric,
  items.blackPeppercorns,
  items.ginger,
  items.coffee,
  items.figs,
  items.radish,
  items.cabbage,
  items.macadamia,
  items.daikon,
  items.mushrooms,
  items.fermentedGarlic,
  items.buckwheat,
  items.mungBeans,
  items.fermentedSoybeans,
  items.plum 
]);

globalThis.d0731 = new ConstantSet([
  items.corn,
  items.figs,
  items.edamame,
  items.almonds,
  items.macadamia,
  items.peanuts,
  items.walnuts,
  items.coffee,
  items.greenTea,
  items.sweetPotaotes,
  items.lime,
  items.mandarin
]);

globalThis.d0801 = new ConstantSet([
  items.redPeppers,
  items.greenPeppers,
  items.yellowPeppers,
  items.blackPeppercorns,
  items.chiaSeeds,
  items.assamTea,
  items.quinoa,
  items.ginger,
  items.sweetPotaotes,
  items.turmeric,
  items.seaweed,
  items.coffee
])

globalThis.d0802 = new ConstantSet([
  items.carrots,
  items.coffee,
  items.almonds,
  items.macadamia,
  items.celery,
  items.tomatoes,
  items.beets,
  items.mandarin,
  items.lime,
  items.greenbeans,
  items.kale,
  items.oatmeal,
  items.blueberries
])

globalThis.d0803 = new ConstantSet([
  items.lentils,
  items.squash,
  items.califlower,
  items.tomatoes,
  items.bokchoy,
  items.macadamia,
  items.almonds,
  items.peanuts,
  items.gobou,
  items.avocado
])

globalThis.d0805 = new ConstantSet([
  items.assamTea,
  items.chiaSeeds,
  items.nutmeg,
  items.ginger,
  items.turmeric,
  items.blackPeppercorns,
  items.tomatoes,
  items.avocado,
  items.fermentedGarlic

])

globalThis.d0806 = new ConstantSet([
  items.seaweed,
  items.quinoa,
  items.redPeppers,
  items.yellowPeppers,
  items.sweetPotaotes,
  items.mandarin,
  items.redOnion,
  items.corn
])

globalThis.d0807 = new ConstantSet([
  items.spinach,
  items.ginger,
  items.kale,
  items.farro,
  items.chickpeas,
  items.almonds,
  items.walnuts,
  items.macadamia,
  items.greenTea,
  items.coffee,
  items.lime,
  items.figs,
  items.garlic,
  items.asian_dong_quai,
  items.asian_solomonsSeal,
  items.asian_huangqi,
  items.redOnion,
  items.greenOnion,
  items.kimchi,
  items.fermentedSoybeans
])

globalThis.d0808 = new ConstantSet([
  items.collardGreen,
  items.redOnion,
  items.greenPeppers,
  items.redPeppers,
  items.yellowPeppers,
  items.purpleKale,
  items.mint,
  items.turmeric,
  items.blackPeppercorns,
  items.ginger,
  items.macadamia,
  items.nutmeg,
  items.cinnamon,
  items.coffee,

])